apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
keywords:
  - Rust
  - vaultwarden
sources:
  - https://github.com/guerzon/vaultwarden
  - https://github.com/dani-garcia/vaultwarden
appVersion: 1.29.0
maintainers:
  - name: Lester Guerzon
    email: guerzon@proton.me
    url: https://github.com/guerzon
  - name: Shivansh Saini
    email: contact@shivanshs9.me
    url: https://shivanshs9.me
version: 0.15.0
